CREATE TABLE LAEGD.LAEGD
(
   AMT CHAR(32) NOT NULL,
   AAR INT NOT NULL,
   LITRA CHAR(1) NOT NULL,
   LAEGDNR INT NOT NULL,
   GLAAR INT,
   GLLITRA CHAR(1),
   RULLETYPE CHAR(32),
   SOGN CHAR(32),
   LAEGDID INT NOT NULL GENERATED ALWAYS AS IDENTITY
)
;

CREATE TABLE LAEGD.RULLE
(
   LAEGDID INT NOT NULL,
   LOEBENR INT NOT NULL,
   GLLAEGDID INT,
   GLLOEBENR INT,
   FADER CHAR(32),
   SOEN CHAR(32),
   FOEDESTED CHAR(32),
   ALDER INT,
   STOERRELSEITOMMER DECIMAL(5,2),
   OPHOLD CHAR(32),
   ANMAERKNINGER CHAR(64),
   FOEDT DATE,
   GEDCOMID CHAR(32),
   NAVN CHAR(64),
   FADERFON CHAR(32),
   SOENFON CHAR(32)
)
;

CREATE UNIQUE INDEX LAEGD.LAEGDIX ON LAEGD.LAEGD
(
   AMT ASC,
   AAR ASC,
   LITRA ASC,
   LAEGDNR ASC
)
;

CREATE UNIQUE INDEX LAEGD.RULLEIX ON LAEGD.RULLE
(
   LAEGDID ASC,
   LOEBENR ASC
)
;

--INSERT INTO LAEGD.LAEGD (AMT, AAR, LITRA, LAEGDNR, GLAAR, GLLITRA, RULLETYPE, SOGN ) VALUES ('Kronborg', 1792, ' ', 6, 0, ' ', 'Hovedrulle', 'Vejby' );
--INSERT INTO LAEGD.LAEGD (AMT, AAR, LITRA, LAEGDNR, GLAAR, GLLITRA, RULLETYPE, SOGN ) VALUES ('Kronborg', 1793, ' ', 6, 1792, ' ', 'Hovedrulle', 'Vejby');
--INSERT INTO LAEGD.LAEGD (AMT, AAR, LITRA, LAEGDNR, GLAAR, GLLITRA, RULLETYPE, SOGN ) VALUES ('Kronborg', 1793, 'A', 6, 1793, ' ', 'Tilgangsrulle', 'Vejby');
--INSERT INTO LAEGD.LAEGD (AMT, AAR, LITRA, LAEGDNR, GLAAR, GLLITRA, RULLETYPE, SOGN ) VALUES ('Kronborg', 1794, 'B', 6, 1793, 'A', 'Tilgangsrulle', 'Vejby');
