CREATE TABLE LAEGD.RULLER
(
   AMT CHAR(32),
   AAR CHAR(32),
   RULLETYPE CHAR(32),
   LAEGDNR INT NOT NULL,
   SOGN CHAR(32),
   LITRA CHAR(32),
   GLLOEBENR INT,
   NYLOEBENR INT,
   FADER CHAR(32),
   SOEN CHAR(32),
   FOEDESTED CHAR(32),
   ALDER INT,
   STOERRELSEITOMMER DECIMAL(5,2),
   OPHOLD CHAR(32),
   ANMAERKNINGER CHAR(64),
   FOEDT DATE,
   GEDCOMID CHAR(32),
   NAVN CHAR(64),
   FADERFON CHAR(32),
   SOENFON CHAR(32)
)
;
